#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIRcomposer.phar" ]; then
    curl -s https://getcomposer.org/installer | $OPENSHIFT_DATA_DIR/../../zend/php-5.4/bin/php -- --install-dir=$OPENSHIFT_DATA_DIR
else
	$OPENSHIFT_DATA_DIR/../../zend/php-5.4/bin/php -d extension=phar.so $OPENSHIFT_DATA_DIR/composer.phar self-update
fi


( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR/php  ; $OPENSHIFT_DATA_DIR/../../zend/php-5.4/bin/php -d extension=phar.so $OPENSHIFT_DATA_DIR/composer.phar install )


unzip $OPENSHIFT_DATA_DIR/mysql/sakila.sql.zip

mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -P "$OPENSHIFT_DB_PORT" [DBNAME] < $OPENSHIFT_DATA_DIR/mysql/sakila.sql