
<div class="panel panel-default">
    <div class="panel-heading">Movies</div>
    <div class="panel-body">
        <p><b>Store : </b><?=$store; ?></p>
    </div>

    <table class="table table-bordered">
        <tbody>
        <?php foreach($pelas as $pela): ?>
            <tr>
                <td><?=$pela["film"]["filmId"]; ?></td>
                <td><?=$pela["film"]["title"]; ?></td>
                <td><?=$pela["film"]["description"];?></td>

                <td>
                    <?php if($pela["stock"] > 0): ?>
                    <a href="<?=$this->url("application", array("action" => "rental","id" => $pela["film"]["filmId"])); ?>">
                    <?php endif?>
                    <?=$pela["stock"]; ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <table class="table table-bordered">

        <ul class="pagination">
            <?php for($i = 0; $i<$pages; $i++){ ?>
                <li>
                    <a href="<?=$this->url("application", array("action" => "index")); ?>?page=<?=($i+1)?>" >
                        <?=($i+1)?>
                    </a>
                </li>
            <?php } ?>

        </ul>


    </table>
</div>


