
<div class="panel panel-default">
    <div class="panel-heading">Rental a DVD</div>
    <div class="panel-body">
        <p><b>Store : </b><?=$store; ?></p>
        <p><b>Stock : </b><?=$filmdata["stock"]; ?></p>
    </div>


    <table class="table table-bordered">
        <tr><td>Film ID:</td><td><?=$filmdata["film"]['filmId']; ?></td></tr>
        <tr><td>Title</td><td><?=$filmdata["film"]['title']; ?></td></tr>
        <tr><td>Description</td><td><?=$filmdata["film"]['description']; ?></td></tr>
        <tr><td>Release Year</td><td><?=$filmdata["film"]['releaseYear']; ?></td></tr>
        <tr><td>Rental Duration</td><td><h4><?=$filmdata["film"]['rentalDuration']; ?> day(s)</h4></td></tr>
        <tr><td>Rental Rate</td><td><h3><?=$filmdata["film"]['rentalRate']; ?></h3></td></tr>
        <tr><td>Length</td><td><?=$filmdata["film"]['length']; ?></td></tr>
        <tr><td>Replacement cost</td><td><?=$filmdata["film"]['replacementCost']; ?></td></tr>
        <tr><td>Rating</td><td><?=$filmdata["film"]['rating']; ?></td></tr>
        <tr><td>Sepecial Features</td><td><?=$filmdata["film"]['specialFeatures']; ?></td></tr>

        </tbody>
    </table>

    <div class="panel-body">

    <p><h4>Copies:</h4></p>

    <table class="table table-bordered">
        <tbody>
        <?php foreach($inventory as $item): ?>
            <tr>
                <td><?=$item["inventoryId"]; ?></td>
                <td>
                <?php if( $avaliable[$item["inventoryId"]] > 0) { ?>
                <a href="<?=$this->url('application', array("action" => "checkout", "id" => $item["inventoryId"])) ?>">
                    Rental copy
                </a>
                <?php } else {?>
                    <span>Not available</span>
                <?php } ?>

                </td>
            </tr>
        <?php endforeach ?>

        </tbody>
    </table>
    </div>
</div>