<div class="panel-group" id="accordion">


<?php foreach ($this->rentals as $rental) : ?>
    <?php $interval = $rental->getRentalDate()->diff( new \Datetime()); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?=$rental->getRentalId(); ?>">
                    Rental ID : <?=$rental->getRentalId(); ?> Overdue <?=$interval->format('%a day(s)') ?></strong>
                </a>
            </h4>
        </div>
        <div id="collapse<?=$rental->getRentalId(); ?>" class="panel-collapse collapse in">
            <div class="panel-body">

    <h5>Inventory ID : <?=$rental->getInventory()->getInventoryId(); ?> </h5>
    <h5>Rental date : <?=$rental->getRentalDate()->format('d/m/Y H:i'); ?> </h5>
    <?php $film = $rental->getInventory()->getFilm(); ?>

    <h4>Film: <b><?=$film->getTitle(); ?></b></h4>
    <h4>Rental duration: <b><?=$film->getRentalDuration(); ?></b> day(s)</h4>

    <div class="alert alert-danger" role="alert">Overdue : <strong><?=$interval->format('%a day(s)') ?></strong></div>



    <p>
    <ul>
        <?php $costumer = $rental->getCustomer(); ?>
        <?php $address = $costumer->getAddress(); ?>

        <li>Customer ID : <?=$costumer->getCustomerId(); ?></li>
        <li>Name : <?=($costumer->getLastname().",".$costumer->getFirstname()); ?></li>
        <li>Email : <?=$costumer->getEmail(); ?></li>
        <li>Address:</li>
        <ul>
            <li><?=$address->getAddress(); ?></li>
            <li>District : <?=$address->getDistrict(); ?></li>
            <li>City : <?=$address->getCity()->getCity(); ?></li>
            <li>Country : <?=$address->getCity()->getCountry()->getCountry(); ?></li>
        </ul>


    </ul>
    </p>

                </div>
        </div>
    </div>


<?php endforeach ?>
</div>
<script>$('.collapse').collapse();</script>