<table class="table table-bordered">
    <tbody>
    <?=$this->form()->openTag($formRental); ?>
    <tr><td colspan="10"></td></tr>
    <tr>
        <td colspan="2"><?php echo $this->formRow($formRental->get('rentalId')); ?></td>
    </tr>
    <tr>
        <td colspan="3"><?php echo $this->formSubmit($formRental->get('submit'));?></td>
    </tr>
    </tbody>
    <?=$this->form()->closeTag($formRental); ?>
</table>

<?php if(isset($rental)) : ?>

    <table class="table table-bordered">
        <tbody>
            <tr><td colspan="3"><h4>Rental Information</h4></td></tr>
            <tr><td colspan="3">Rental Date : <b><?=$rental->getRentalDate()->format('d/m/Y H:i'); ?></b></td></tr>
            <tr><td colspan="1">Film : </td><td><?=$film->getTitle(); ?></td></tr>
            <tr><td colspan="1">Rental duration : </td><td><?=$film->getRentalDuration(); ?> day(s)</td></tr>
        </tbody>
    </table>

    <table class="table table-bordered">
        <tbody>
        <?php $this->formReturn->setAttribute('action', $this->url('application', array('action' => 'return'))); ?>
        <?php $formReturn->prepare(); ?>

        <?=$this->form()->openTag($formReturn); ?>

        <?php echo $this->formRow($formReturn->get('rentalId')); ?>
        <tr><td colspan="3"><h4>Customer Information</h4></td></tr>
        <tr>
            <?php $customer = $rental->getCustomer(); ?>
            <td><?=$customer->getCustomerId() ?></td>
            <td><?=$customer->getLastName() ?>, <?=$customer->getFirstName() ?></td>
            <td><?=$customer->getEmail(); ?></td>
        </tr>

        <tr>
            <td colspan="3"><?php echo $this->formSubmit($formReturn->get('submit'));?></td>
        </tr>
        </tbody>
        <?=$this->form()->closeTag($formReturn); ?>
    </table>
<?php endif ?>